require('core.plugin_config.lualine')
require('core.plugin_config.telescope')
require('core.plugin_config.tokyonight')
require('core.plugin_config.lsp_config')
require('core.plugin_config.autocompletions')
